export const PYTHON_IMAGE = 'python:3.12-slim';

// THIS WILL REPRESENT HEADER SIZE OF DOCKER STREAM
// DOCKER STREAM HEADER WILL CONTAIN DATA ABOUT TYPES OF STREAM I.E stdout/stderr
// AND THE LENGTH OF DATA
export const DOCKER_STREAM_HEADER_SIZE = 8; // 8 BYTES
